export {
  SEO_DEFAULTS,
  generateMetaTags,
  getOrganizationSchema,
  getProductSchema,
  getFAQSchema,
  getBreadcrumbSchema,
  getDestinationSchema,
  getArticleSchema,
  getLocalBusinessSchema,
  generateSitemap,
  getRobotsTxt,
  getCanonicalUrl,
  generateSocialShareImage,
  SEO_CHECKLIST,
  type SEOConfig,
  type StructuredData,
  type SitemapUrl,
} from './SEOService';
