/**
 * Server-side Mock Data
 * Used when database is not connected
 * This file doesn't import local assets for server bundle compatibility
 * Types are flexible to match frontend expectations
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyDestination = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyLodge = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyBooking = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyStats = any;

// Sample image URLs from Unsplash for server-side use
const SAMPLE_IMAGES = {
  safariHero: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
  luxuryLodge: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80',
};

export const MOCK_DESTINATIONS: AnyDestination[] = [
  {
    id: 'dest-masai-mara',
    name: 'Masai Mara National Reserve',
    tagline: 'World-Famous Great Wildebeest Migration & Big Cat Empire',
    country: 'Kenya',
    region: 'Narok County, Rift Valley',
    category: 'Savanna & Plains',
    image: SAMPLE_IMAGES.safariHero,
    heroImage: SAMPLE_IMAGES.safariHero,
    gallery: [
      SAMPLE_IMAGES.safariHero,
      SAMPLE_IMAGES.luxuryLodge,
      'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.98,
    reviewsCount: 847,
    startingPrice: 2800,
    durationDays: 4,
    bestMonths: ['January', 'February', 'July', 'August', 'September', 'October'],
    wildlifeHighlights: ['The Big Five', 'Great Wildebeest Migration'],
    bigFiveProbability: { lion: 95, leopard: 85, elephant: 90, rhino: 40, buffalo: 90 },
    description: 'The Masai Mara is Kenya\'s most famous wildlife reserve, renowned for the Great Wildebeest Migration and exceptional big cat populations. Experience the raw beauty of Africa.',
    highlights: ['Great Wildebeest Migration', 'Big Cat sightings', 'Hot air balloon safaris', 'Masai cultural experiences'],
    coordinates: { lat: -1.4061, lng: 35.0173 },
    featured: true,
    ecoScore: 9.8,
  },
  {
    id: 'dest-serengeti',
    name: 'Serengeti National Park',
    tagline: 'Endless Plains & The Greatest Wildlife Show on Earth',
    country: 'Tanzania',
    region: 'Mara Region',
    category: 'Savanna & Plains',
    image: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?auto=format&fit=crop&w=1200&q=80',
    heroImage: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?auto=format&fit=crop&w=1200&q=80',
    gallery: [],
    rating: 4.96,
    reviewsCount: 723,
    startingPrice: 3200,
    durationDays: 5,
    bestMonths: ['June', 'July', 'August', 'September', 'October', 'November'],
    wildlifeHighlights: ['Great Wildebeest Migration', 'The Big Five'],
    bigFiveProbability: { lion: 95, leopard: 85, elephant: 90, rhino: 30, buffalo: 85 },
    description: 'The Serengeti offers an unparalleled safari experience across vast golden savannahs.',
    highlights: ['Wildebeest Migration', 'Balloon safaris', 'Luxury camps', 'Photographic safaris'],
    coordinates: { lat: -2.3333, lng: 34.8333 },
    featured: true,
    ecoScore: 9.7,
  },
  {
    id: 'dest-volcanoes',
    name: 'Volcanoes National Park',
    tagline: 'Mountain Gorilla Sanctuary & Dian Fossey\'s Legacy',
    country: 'Rwanda',
    region: 'Northern Province',
    category: 'Crater & Highlands',
    image: 'https://images.unsplash.com/photo-1548560781-a1f7f9c0b1f1?auto=format&fit=crop&w=1200&q=80',
    heroImage: 'https://images.unsplash.com/photo-1548560781-a1f7f9c0b1f1?auto=format&fit=crop&w=1200&q=80',
    gallery: [],
    rating: 4.95,
    reviewsCount: 456,
    startingPrice: 4500,
    durationDays: 3,
    bestMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    wildlifeHighlights: ['Mountain Gorillas & Primates'],
    bigFiveProbability: { lion: 0, leopard: 10, elephant: 40, rhino: 0, buffalo: 60 },
    description: 'Home to the endangered mountain gorilla, this park offers once-in-a-lifetime encounters.',
    highlights: ['Gorilla trekking', 'Golden monkey tracking', 'Dian Fossey tomb hike', 'Volcano views'],
    coordinates: { lat: -1.4833, lng: 29.4833 },
    featured: true,
    ecoScore: 9.9,
  },
  {
    id: 'dest-bwindi',
    name: 'Bwindi Impenetrable Forest',
    tagline: 'Ancient Rainforest & Rare Mountain Gorillas',
    country: 'Uganda',
    region: 'Southwestern Uganda',
    category: 'Impenetrable Forest',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80',
    heroImage: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80',
    gallery: [],
    rating: 4.93,
    reviewsCount: 389,
    startingPrice: 4200,
    durationDays: 3,
    bestMonths: ['January', 'February', 'June', 'July', 'August', 'September', 'December'],
    wildlifeHighlights: ['Mountain Gorillas & Primates', 'Flamingos & Birding'],
    bigFiveProbability: { lion: 0, leopard: 5, elephant: 30, rhino: 0, buffalo: 40 },
    description: 'A UNESCO World Heritage site, Bwindi is one of Africa\'s most ancient rainforests.',
    highlights: ['Gorilla habituation experience', 'Bird watching', 'Forest walks', 'Community tours'],
    coordinates: { lat: -0.9833, lng: 29.6167 },
    featured: false,
    ecoScore: 10.0,
  },
];

export const MOCK_ITINERARIES: AnyDestination[] = [
  {
    id: 'itinerary-great-migration',
    title: 'Great Migration Safari',
    subtitle: 'Witness the circle of life on the Serengeti plains',
    country: 'Tanzania',
    region: 'Serengeti',
    category: 'Classic Safari',
    durationDays: 7,
    maxGroupSize: 8,
    pricePerPerson: 3500,
    minimumAge: 4,
    image: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?auto=format&fit=crop&w=1200&q=80',
    heroImage: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?auto=format&fit=crop&w=1200&q=80',
    rating: 4.95,
    reviewsCount: 234,
    highlights: ['Witness the Great Migration', 'Big Five game drives', 'Hot air balloon safari', 'Luxury tented camp'],
    included: ['All meals', 'Park fees', 'Game drives', 'Accommodation', 'Airport transfers'],
    excluded: ['International flights', 'Travel insurance', 'Visa fees', 'Personal expenses'],
    itineraryDays: [],
    description: 'Experience the most spectacular wildlife event on Earth.',
    bestSeason: 'July - October',
    difficulty: 'Easy',
    featured: true,
  },
];

export const MOCK_LODGES: AnyLodge[] = [
  {
    id: 'lodge-mara-bush-camp',
    name: 'Mara Bush Camp',
    tagline: 'Intimate Safari Experience in the Heart of the Mara',
    country: 'Kenya',
    region: 'Masai Mara',
    category: 'Luxury Tented Camp',
    image: SAMPLE_IMAGES.luxuryLodge,
    heroImage: SAMPLE_IMAGES.luxuryLodge,
    gallery: [],
    rating: 4.9,
    reviewsCount: 156,
    pricePerNight: 850,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['WiFi', 'Hot shower', 'Laundry', 'Bar', 'Restaurant'],
    description: 'An intimate tented camp offering authentic safari experiences.',
    highlights: ['Prime location', 'Expert guides', 'Gourmet dining', 'Sundowner cocktails'],
    coordinates: { lat: -1.4061, lng: 35.0173 },
    featured: true,
  },
  {
    id: 'lodge-serengeti-sopa',
    name: 'Serengeti Sopa Lodge',
    tagline: 'Luxury Among the Wildlife',
    country: 'Tanzania',
    region: 'Serengeti',
    category: 'Safari Lodge',
    image: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80',
    heroImage: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80',
    gallery: [],
    rating: 4.85,
    reviewsCount: 203,
    pricePerNight: 1200,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ['Pool', 'WiFi', 'Spa', 'Bar', 'Restaurant', 'Game drives'],
    description: 'Elegant lodge with stunning views of the Serengeti plains.',
    highlights: ['Infinity pool', 'Panoramic views', 'Spa services', 'Cultural performances'],
    coordinates: { lat: -2.3333, lng: 34.8333 },
    featured: true,
  },
];

export const MOCK_BOOKING_ADDONS: AnyBooking[] = [
  { id: 'addon-1', name: 'Airport Transfer', description: 'Round-trip transfers', priceUSD: 150, perPerson: false, icon: 'plane' },
  { id: 'addon-2', name: 'Travel Insurance', description: 'Comprehensive coverage', priceUSD: 45, perPerson: true, icon: 'shield' },
  { id: 'addon-3', name: 'Photography Safari', description: 'Pro photographer guide', priceUSD: 200, perPerson: true, icon: 'camera' },
  { id: 'addon-4', name: 'Bush Dinner', description: 'Romantic dinner', priceUSD: 120, perPerson: true, icon: 'utensils' },
  { id: 'addon-5', name: 'Hot Air Balloon', description: 'Sunrise flight', priceUSD: 450, perPerson: true, icon: 'cloud' },
];

export const MOCK_USER_BOOKINGS: AnyBooking[] = [
  {
    id: 'booking-001',
    bookingRef: 'IDN-MARA-2024-001',
    destinationId: 'dest-masai-mara',
    destinationName: 'Masai Mara National Reserve',
    startDate: '2024-07-15',
    endDate: '2024-07-19',
    guests: { adults: 2, children: 0 },
    totalPrice: 5600,
    currency: 'USD',
    status: 'Confirmed',
    paymentStatus: 'Paid in Full',
    createdAt: '2024-06-01T10:30:00Z',
    image: SAMPLE_IMAGES.safariHero,
  },
  {
    id: 'booking-002',
    bookingRef: 'IDN-SERENGETI-2024-002',
    destinationId: 'dest-serengeti',
    destinationName: 'Serengeti National Park',
    startDate: '2024-08-20',
    endDate: '2024-08-27',
    guests: { adults: 2, children: 2 },
    totalPrice: 8400,
    currency: 'USD',
    status: 'Pending Approval',
    paymentStatus: 'Deposit Paid (30%)',
    createdAt: '2024-06-15T14:20:00Z',
    image: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?auto=format&fit=crop&w=1200&q=80',
  },
];

export const MOCK_ADMIN_STATS: AnyStats = {
  totalRevenueUSD: 2485000,
  activeExpeditionsCount: 38,
  totalTravelersCount: 1420,
  verifiedRangersCount: 84,
  popularParksCount: 12,
  monthlyBookings: [
    { month: 'Jan', bookings: 45, revenueUSD: 125000 },
    { month: 'Feb', bookings: 52, revenueUSD: 142000 },
    { month: 'Mar', bookings: 48, revenueUSD: 138000 },
    { month: 'Apr', bookings: 38, revenueUSD: 95000 },
    { month: 'May', bookings: 35, revenueUSD: 88000 },
    { month: 'Jun', bookings: 62, revenueUSD: 185000 },
    { month: 'Jul', bookings: 95, revenueUSD: 320000 },
    { month: 'Aug', bookings: 102, revenueUSD: 355000 },
    { month: 'Sep', bookings: 88, revenueUSD: 295000 },
    { month: 'Oct', bookings: 72, revenueUSD: 210000 },
    { month: 'Nov', bookings: 58, revenueUSD: 165000 },
    { month: 'Dec', bookings: 78, revenueUSD: 235000 },
  ],
};
