/**
 * Default Booking Addons Content
 * Premium safari add-on experiences
 */

export const DEFAULT_ADDONS = [
  {
    id: 'addon-balloon',
    name: 'Dawn Hot Air Balloon Safari & Champagne Breakfast',
    priceUSD: 520,
    perPerson: true,
    description: '1-hour sunrise flight over the plains followed by silver-service champagne breakfast served live in the open bush.',
    icon: 'Wind',
    category: 'Aerial Experience',
    available: true,
  },
  {
    id: 'addon-gorilla-permit',
    name: 'Gorilla Habituation VIP Full-Day Access Permit',
    priceUSD: 1500,
    perPerson: true,
    description: 'Spend up to 4 full hours with wild mountain gorilla researchers and wild gorilla family instead of the standard 1 hour.',
    icon: 'Trees',
    category: 'Primate Experience',
    available: true,
  },
  {
    id: 'addon-photo-guide',
    name: 'Private Professional Wildlife Photographer & Rig Vehicle',
    priceUSD: 650,
    perPerson: false,
    description: 'Custom open Land Cruiser equipped with low-angle camera mounts, beanbags, high-speed charging, and 1-on-1 photo guide.',
    icon: 'Camera',
    category: 'Photography',
    available: true,
  },
  {
    id: 'addon-night-drive',
    name: 'Infra-Red Thermal Night Game Drive in Private Reserve',
    priceUSD: 220,
    perPerson: true,
    description: 'Guaranteed night safari with specialized spotters tracking leopards, lions on hunts, bushbabies, and nocturnal cats.',
    icon: 'Moon',
    category: 'Game Drive',
    available: true,
  },
  {
    id: 'addon-helicopter',
    name: 'Scenic Helicopter Glacier Flyover over Mt. Kilimanjaro',
    priceUSD: 850,
    perPerson: true,
    description: '30-minute private doors-off helicopter tour skimming over the glaciers and crater peak of Mount Kilimanjaro.',
    icon: 'Plane',
    category: 'Aerial Experience',
    available: true,
  },
  {
    id: 'addon-bush-dinner',
    name: 'Romantic Bush Dinner Under the Stars',
    priceUSD: 180,
    perPerson: true,
    description: 'Private candlelit dinner in the bush with white linens, silver service, and a personal chef cooking gourmet cuisine.',
    icon: 'UtensilsCrossed',
    category: 'Dining',
    available: true,
  },
  {
    id: 'addon-sundowner',
    name: 'Kopje Sundowner & Canapés Experience',
    priceUSD: 95,
    perPerson: false,
    description: 'Sunset drinks served atop a granite kopje with panoramic savanna views, artisan gin selection, and gourmet canapés.',
    icon: 'Sunset',
    category: 'Dining',
    available: true,
  },
  {
    id: 'addon-cultural',
    name: 'Maasai Warrior Dance & Village Experience',
    priceUSD: 120,
    perPerson: true,
    description: 'Authentic visit to a traditional Maasai manyatta with warrior dances, fire-making demonstration, and beadwork workshop.',
    icon: 'Users',
    category: 'Cultural',
    available: true,
  },
  {
    id: 'addon-spa',
    name: 'Luxury Safari Spa Treatment',
    priceUSD: 200,
    perPerson: true,
    description: '60-minute signature spa treatment using African botanicals, available at select luxury lodges.',
    icon: 'Sparkles',
    category: 'Wellness',
    available: true,
  },
];

export type DefaultAddon = typeof DEFAULT_ADDONS[number];
