/**
 * Default Destinations Content
 * Premium wildlife destination data for East Africa
 */

import safariHeroImg from '../../assets/images/safari_hero_1784973880507.jpg';
import luxuryLodgeImg from '../../assets/images/luxury_lodge_1784973897035.jpg';

export const DEFAULT_DESTINATIONS = [
  {
    id: 'dest-masai-mara',
    name: 'Masai Mara National Reserve',
    tagline: 'World-Famous Great Wildebeest Migration & Big Cat Empire',
    country: 'Kenya' as const,
    region: 'Narok County, Rift Valley',
    category: 'Savanna & Plains' as const,
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
      'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.95,
    reviewsCount: 328,
    startingPrice: 3800,
    durationDays: 5,
    bestMonths: ['July', 'August', 'September', 'October', 'December', 'January'],
    wildlifeHighlights: ['The Big Five', 'Great Wildebeest Migration', 'Predator Tracking'],
    bigFiveProbability: {
      lion: 98,
      leopard: 85,
      elephant: 95,
      rhino: 65,
      buffalo: 96,
    },
    description: 'The Masai Mara is one of Africa\'s greatest wildlife havens. Celebrated for its high lion population, endless golden savannas, and the awe-inspiring river crossings during the annual Great Wildebeest Migration.',
    highlights: [
      'Hot air balloon safari with bush champagne breakfast at dawn',
      'Witness Mara River wildebeest and zebra crocodile crossings',
      'Private game drives guided by authentic Maasai naturalists',
      'Night game drives in exclusive private conservancies',
    ],
    coordinates: { lat: -1.4061, lng: 35.1328 },
    featured: true,
    ecoScore: 9.9,
    weather: {
      currentTempC: 27,
      condition: 'Sunny Savanna Breeze',
      lowTempC: 14,
      highTempC: 29,
      humidity: 45,
      rainfallMm: 8,
      bestVisitingCondition: 'July through October offers prime wildebeest migration herd crossings along Mara River.',
      monthly: [
        { month: 'Jan', tempC: 28, rainfall: 'Low' },
        { month: 'Feb', tempC: 29, rainfall: 'Low' },
        { month: 'Mar', tempC: 28, rainfall: 'Moderate' },
        { month: 'Apr', tempC: 26, rainfall: 'High' },
        { month: 'May', tempC: 25, rainfall: 'Moderate' },
        { month: 'Jun', tempC: 26, rainfall: 'Low' },
        { month: 'Jul', tempC: 27, rainfall: 'Low' },
        { month: 'Aug', tempC: 28, rainfall: 'Low' },
        { month: 'Sep', tempC: 28, rainfall: 'Low' },
        { month: 'Oct', tempC: 28, rainfall: 'Low' },
        { month: 'Nov', tempC: 26, rainfall: 'Moderate' },
        { month: 'Dec', tempC: 27, rainfall: 'Low' },
      ],
    },
    parkInfo: {
      entryFeeUSD: 100,
      vehicleFeeUSD: 40,
      operatingHours: '06:00 AM - 06:30 PM Daily (Gate strict entry)',
      conservationStatus: 'Protected National Reserve / Maasai Conservancy Trust',
      totalAreaSqKm: 1510,
      rules: [
        'Maintain minimum 25 meters distance from lions and leopards',
        'Off-roading strictly prohibited inside core reserve',
        'No feeding or shouting at wildlife',
        'Drones prohibited without Kenya Film Classification & KWS License',
      ],
      rangerContact: '+254 720 100 800',
      emergencyHelpline: '+254 711 999 111 (Kenya Wildlife Service Hotline)',
      officialWebsite: 'https://www.masaimara.com',
    },
    wildlifeInfo: [
      { id: 'w1', species: 'African Lion (Marsh Pride)', sightingProbability: 'Guaranteed' as const, probabilityPercentage: 98, description: 'Iconic big cat coalitions dominating the Talek & Mara riverbanks.', bestSpottingTime: '06:00 AM Dawn & 05:30 PM Dusk' },
      { id: 'w2', species: 'Great Wildebeest Herd', sightingProbability: 'Seasonal' as const, probabilityPercentage: 95, description: 'Over 1.5 million wildebeest crossing from Serengeti into Mara.', bestSpottingTime: 'Mid-day River Crossings (11:00 AM - 02:00 PM)' },
      { id: 'w3', species: 'African Savannah Elephant', sightingProbability: 'High' as const, probabilityPercentage: 95, description: 'Gentle giant herds roaming the acacia woodlands.', bestSpottingTime: 'All day near Musiara Swamp' },
      { id: 'w4', species: 'African Leopard', sightingProbability: 'High' as const, probabilityPercentage: 85, description: 'Solitary predators resting on high sausage tree branches.', bestSpottingTime: 'Late afternoon around Olare Orok' },
      { id: 'w5', species: 'Black Rhinoceros', sightingProbability: 'Moderate' as const, probabilityPercentage: 65, description: 'Endangered black rhinos roaming the dense thickets.', bestSpottingTime: 'Early morning misty valleys' },
    ],
    nearbyAttractions: [
      { id: 'a1', name: 'Mara River Crossing Point 4', type: 'River Crossing Point', distanceKm: 12.5, description: 'Dramatic crossing site lined with giant Nile crocodiles and steep muddy embankments.' },
      { id: 'a2', name: 'Ololaimutiek Maasai Manyatta', type: 'Cultural Village', distanceKm: 8.2, description: 'Authentic Maasai cultural homestead with traditional dances and beadwork craft masters.' },
      { id: 'a3', name: 'Musiara Swamp Waterhole', type: 'River Crossing Point', distanceKm: 15.0, description: 'Lush marshland where large herds of elephants bathe and lions ambush prey.' },
      { id: 'a4', name: 'Keekorok Airstrip', type: 'Airstrip / Heliport', distanceKm: 5.0, description: 'Primary bush aviation strip with direct charter flights to Nairobi Wilson Airport.' },
    ],
    travelTips: [
      { id: 't1', category: 'Packing' as const, title: 'Layered Warm Clothing for Dawn', content: 'Mornings in the Mara are chilly (12°C). Bring a windbreaker, fleece jacket, and safari hat that fastens.' },
      { id: 't2', category: 'Best Photography' as const, title: 'Telephoto Lens & Beanbag', content: 'Bring 100-400mm or 200-600mm lenses. Dust covers and window-mount beanbags are essential inside 4x4 vehicles.' },
      { id: 't3', category: 'Health & Visas' as const, title: 'Yellow Fever & Malarial Precautions', content: 'Malaria risk is low to moderate. Anti-malarials recommended along with insect repellent for sundowner hours.' },
      { id: 't4', category: 'Etiquette' as const, title: 'Tipping Guidelines', content: 'Recommended tipping is $20-$30 USD per day for your driver-guide and $15 USD for camp staff.' },
    ],
  },
  {
    id: 'dest-serengeti',
    name: 'Serengeti National Park',
    tagline: 'Endless Golden Savannas & Year-Round Migration Tracking',
    country: 'Tanzania' as const,
    region: 'Mara & Simiyu Regions',
    category: 'Savanna & Plains' as const,
    image: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.98,
    reviewsCount: 412,
    startingPrice: 4200,
    durationDays: 7,
    bestMonths: ['June', 'July', 'August', 'September', 'October', 'February'],
    wildlifeHighlights: ['The Big Five', 'Great Wildebeest Migration', 'Predator Tracking'],
    bigFiveProbability: {
      lion: 99,
      leopard: 90,
      elephant: 94,
      rhino: 72,
      buffalo: 98,
    },
    description: 'A UNESCO World Heritage Site boasting over 14,000 square kilometers of pristine wilderness. Home to the legendary Great Migration, vast pride coalitions of lions, cheetahs on Kopjes, and ultra-luxurious mobile tented camps.',
    highlights: [
      'Follow mobile migration camps tracking herds across Central, Northern, and Southern Serengeti',
      'Spot black rhinos in the secluded Moru Kopjes area',
      'Exquisite sunset sundowners served on dramatic granite Kopjes',
    ],
    coordinates: { lat: -2.3333, lng: 34.8333 },
    featured: true,
    ecoScore: 9.8,
    weather: {
      currentTempC: 26,
      condition: 'Clear Savanna Skies',
      lowTempC: 15,
      highTempC: 28,
      humidity: 50,
      rainfallMm: 5,
      bestVisitingCondition: 'June-October for river crossings; January-February for Ndutu calving season.',
      monthly: [
        { month: 'Jan', tempC: 27, rainfall: 'Low' },
        { month: 'Feb', tempC: 28, rainfall: 'Low' },
        { month: 'Mar', tempC: 27, rainfall: 'Moderate' },
        { month: 'Apr', tempC: 25, rainfall: 'High' },
        { month: 'May', tempC: 24, rainfall: 'High' },
        { month: 'Jun', tempC: 25, rainfall: 'Low' },
        { month: 'Jul', tempC: 26, rainfall: 'Low' },
        { month: 'Aug', tempC: 27, rainfall: 'Low' },
        { month: 'Sep', tempC: 28, rainfall: 'Low' },
        { month: 'Oct', tempC: 28, rainfall: 'Low' },
        { month: 'Nov', tempC: 26, rainfall: 'Moderate' },
        { month: 'Dec', tempC: 27, rainfall: 'Moderate' },
      ],
    },
    parkInfo: {
      entryFeeUSD: 82,
      vehicleFeeUSD: 50,
      operatingHours: '06:00 AM - 06:00 PM Daily',
      conservationStatus: 'UNESCO World Heritage Site / TANAPA National Park',
      totalAreaSqKm: 14763,
      rules: [
        'Strict 50 km/h speed limit on main transit routes',
        'Do not leave vehicle except at designated picnic sites',
        'No plastic single-use bags permitted in Tanzania',
      ],
      rangerContact: '+255 28 262 1515',
      emergencyHelpline: '+255 784 100 200 (TANAPA Emergency)',
      officialWebsite: 'https://www.serengeti.org',
    },
    wildlifeInfo: [
      { id: 'sw1', species: 'African Lion', sightingProbability: 'Guaranteed' as const, probabilityPercentage: 99, description: 'Over 3,000 resident lions living across plains and kopjes.', bestSpottingTime: 'Early morning drives' },
      { id: 'sw2', species: 'Cheetah Coalition', sightingProbability: 'High' as const, probabilityPercentage: 88, description: 'Fastest land animals scanning the plains from granite Kopjes.', bestSpottingTime: 'Mid-morning hunting window' },
      { id: 'sw3', species: 'Black Rhino (Moru Kopjes)', sightingProbability: 'Moderate' as const, probabilityPercentage: 72, description: 'Protected rhino sanctuary under 24/7 anti-poaching patrol.', bestSpottingTime: 'Dawn in Moru Kopjes' },
    ],
    nearbyAttractions: [
      { id: 'sa1', name: 'Moru Kopjes & Gong Rock', type: 'Volcanic Crater', distanceKm: 18.0, description: 'Ancient granite rock formations featuring Maasai rock paintings and ancient rhino sanctuaries.' },
      { id: 'sa2', name: 'Seronera Visitors Center', type: 'Cultural Village', distanceKm: 4.5, description: 'Educational wildlife hall, cafe, and historical migration exhibit.' },
    ],
    travelTips: [
      { id: 'st1', category: 'Health & Visas' as const, title: 'Tanzania eVisa & Plastic Bag Ban', content: 'Apply for Tanzania eVisa online prior to arrival. Tanzania strictly enforces a ban on single-use plastic carrier bags.' },
      { id: 'st2', category: 'Packing' as const, title: 'Neutral Khaki Clothing', content: 'Avoid bright blue or black clothes as they attract tsetse flies in wooded areas.' },
    ],
  },
  {
    id: 'dest-bwindi',
    name: 'Bwindi Impenetrable Forest',
    tagline: 'Mist-Shrouded Sanctuary of Mountain Gorillas',
    country: 'Uganda' as const,
    region: 'Kanungu District, South-Western Uganda',
    category: 'Impenetrable Forest' as const,
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
      'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.92,
    reviewsCount: 287,
    startingPrice: 4500,
    durationDays: 3,
    bestMonths: ['June', 'July', 'August', 'September', 'December', 'January', 'February'],
    wildlifeHighlights: ['Mountain Gorillas & Primates'],
    bigFiveProbability: {
      lion: 0,
      leopard: 5,
      elephant: 35,
      rhino: 0,
      buffalo: 45,
    },
    description: 'A UNESCO World Heritage Site and one of Africa\'s most ancient rainforests at over 25,000 years old. Home to nearly half of the world\'s remaining mountain gorilla population and 12 other primate species.',
    highlights: [
      'Trek through misty forest to encounter wild mountain gorilla families',
      'Discover 350+ bird species including 23 Albertine Rift endemics',
      'Walk with Batwa forest guides sharing ancient hunter-gatherer traditions',
    ],
    coordinates: { lat: -0.9833, lng: 29.6167 },
    featured: true,
    ecoScore: 10.0,
    weather: {
      currentTempC: 20,
      condition: 'Misty Rainforest',
      lowTempC: 12,
      highTempC: 24,
      humidity: 85,
      rainfallMm: 15,
      bestVisitingCondition: 'June-August and December-February for drier trekking conditions.',
      monthly: [
        { month: 'Jan', tempC: 20, rainfall: 'Low' },
        { month: 'Feb', tempC: 21, rainfall: 'Low' },
        { month: 'Mar', tempC: 20, rainfall: 'Moderate' },
        { month: 'Apr', tempC: 19, rainfall: 'High' },
        { month: 'May', tempC: 18, rainfall: 'High' },
        { month: 'Jun', tempC: 19, rainfall: 'Low' },
        { month: 'Jul', tempC: 20, rainfall: 'Low' },
        { month: 'Aug', tempC: 20, rainfall: 'Low' },
        { month: 'Sep', tempC: 21, rainfall: 'Low' },
        { month: 'Oct', tempC: 20, rainfall: 'Moderate' },
        { month: 'Nov', tempC: 19, rainfall: 'High' },
        { month: 'Dec', tempC: 20, rainfall: 'Low' },
      ],
    },
    parkInfo: {
      entryFeeUSD: 600,
      vehicleFeeUSD: 30,
      operatingHours: '08:00 AM - 05:00 PM Daily (Permits required)',
      conservationStatus: 'UNESCO World Heritage Site / Uganda Wildlife Authority',
      totalAreaSqKm: 331,
      rules: [
        'Minimum age 15 years for gorilla trekking',
        'Maximum 8 visitors per gorilla family per day',
        'Maintain 7 meter distance from gorillas at all times',
        'No flash photography permitted',
      ],
      rangerContact: '+256 414 755 100',
      emergencyHelpline: '+256 772 100 200 (UWA Emergency)',
      officialWebsite: 'https://www.ugandawildlife.org',
    },
    wildlifeInfo: [
      { id: 'bw1', species: 'Mountain Gorilla', sightingProbability: 'Guaranteed' as const, probabilityPercentage: 98, description: 'Approximately 459 individuals across 50 habituated family groups.', bestSpottingTime: 'Any time during 1-hour permit allocation' },
      { id: 'bw2', species: 'Chimpanzee', sightingProbability: 'High' as const, probabilityPercentage: 85, description: 'Habituated chimp families in the Habinyanja and Rushegura sectors.', bestSpottingTime: 'Morning chimp treks' },
    ],
    nearbyAttractions: [
      { id: 'ba1', name: 'Lake Bunyonyi', type: 'Waterfalls', distanceKm: 25.0, description: 'Deep crater lake with terraced shores and 29 islands of legend.' },
    ],
    travelTips: [
      { id: 'bwt1', category: 'Packing' as const, title: 'Waterproof Gear & Sturdy Boots', content: 'Expect muddy, steep terrain. Pack waterproof bags, gaiters, and thick hiking socks.' },
      { id: 'bwt2', category: 'Health & Visas' as const, title: 'Yellow Fever Certificate', content: 'Required for Uganda entry. Also recommended: Typhoid and Hepatitis A vaccinations.' },
    ],
  },
  {
    id: 'dest-volcanoes',
    name: 'Volcanoes National Park',
    tagline: 'Mountain Gorilla Sanctuary & Dian Fossey\'s Legacy',
    country: 'Rwanda' as const,
    region: 'Northern Province',
    category: 'Crater & Highlands' as const,
    image: 'https://images.unsplash.com/photo-1548560781-a1f7f9c0b1f1?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1548560781-a1f7f9c0b1f1?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
    ],
    rating: 4.96,
    reviewsCount: 356,
    startingPrice: 4800,
    durationDays: 3,
    bestMonths: ['January', 'February', 'June', 'July', 'August', 'September', 'December'],
    wildlifeHighlights: ['Mountain Gorillas & Primates'],
    bigFiveProbability: {
      lion: 0,
      leopard: 5,
      elephant: 25,
      rhino: 0,
      buffalo: 40,
    },
    description: 'Rwanda\'s premier national park and home to the legendary Dian Fossey\'s Karisoke Research Center. Trek through misty volcanic slopes to encounter golden monkeys and one-third of the world\'s mountain gorillas.',
    highlights: [
      'Trek habituated gorilla families like the Susa group immortalized by Dian Fossey',
      'Golden monkey tracking through bamboo forests',
      'Hike to Dian Fossey\'s original tomb near Mount Karisimbi',
    ],
    coordinates: { lat: -1.4833, lng: 29.4833 },
    featured: true,
    ecoScore: 9.9,
    weather: {
      currentTempC: 18,
      condition: 'Alpine Mist',
      lowTempC: 8,
      highTempC: 22,
      humidity: 75,
      rainfallMm: 12,
      bestVisitingCondition: 'June-September offers clearest volcano views and drier trails.',
      monthly: [
        { month: 'Jan', tempC: 18, rainfall: 'Low' },
        { month: 'Feb', tempC: 19, rainfall: 'Low' },
        { month: 'Mar', tempC: 18, rainfall: 'Moderate' },
        { month: 'Apr', tempC: 17, rainfall: 'High' },
        { month: 'May', tempC: 16, rainfall: 'High' },
        { month: 'Jun', tempC: 17, rainfall: 'Low' },
        { month: 'Jul', tempC: 18, rainfall: 'Low' },
        { month: 'Aug', tempC: 18, rainfall: 'Low' },
        { month: 'Sep', tempC: 19, rainfall: 'Low' },
        { month: 'Oct', tempC: 18, rainfall: 'Moderate' },
        { month: 'Nov', tempC: 17, rainfall: 'High' },
        { month: 'Dec', tempC: 18, rainfall: 'Low' },
      ],
    },
    parkInfo: {
      entryFeeUSD: 1500,
      vehicleFeeUSD: 50,
      operatingHours: '07:00 AM - 05:00 PM Daily (Permits required)',
      conservationStatus: 'Volcanoes National Park / Rwanda Development Board',
      totalAreaSqKm: 160,
      rules: [
        'Minimum age 15 years for gorilla trekking',
        'Maximum 8 visitors per gorilla family per day',
        'Strict 1-hour maximum time with each gorilla group',
        'No drones permitted in the park',
      ],
      rangerContact: '+250 252 535 400',
      emergencyHelpline: '+250 788 300 300 (RDB Emergency)',
      officialWebsite: 'https://www.rwandatourism.com',
    },
    wildlifeInfo: [
      { id: 'v1', species: 'Mountain Gorilla', sightingProbability: 'Guaranteed' as const, probabilityPercentage: 98, description: '10 habituated gorilla families available for trekking with 15 habituation permits daily.', bestSpottingTime: 'Any time during 1-hour permit allocation' },
      { id: 'v2', species: 'Golden Monkey', sightingProbability: 'Guaranteed' as const, probabilityPercentage: 95, description: 'Endemic blue monkey subspecies found only in the Virunga volcanic chain.', bestSpottingTime: 'Morning bamboo forest treks' },
    ],
    nearbyAttractions: [
      { id: 'va1', name: 'Dian Fossey Tomb Hike', type: 'Volcanic Crater', distanceKm: 8.0, description: 'Full-day hike to the original Karisoke Research Center and Dian Fossey\'s gravesite.' },
      { id: 'va2', name: 'Lake Kivu Beaches', type: 'Waterfalls', distanceKm: 45.0, description: 'Stunning crescent beaches on Lake Kivu with boat excursions to Nyamyumba Hot Springs.' },
    ],
    travelTips: [
      { id: 'vt1', category: 'Packing' as const, title: 'Mountain Layers & Rain Gear', content: 'Weather changes rapidly. Pack layers, rain poncho, and sun protection for high altitude trekking.' },
      { id: 'vt2', category: 'Health & Visas' as const, title: 'Rwanda Visa on Arrival', content: 'Most nationalities receive 30-day visa on arrival ($30-$50). Yellow fever vaccine required.' },
    ],
  },
];

export type DefaultDestination = typeof DEFAULT_DESTINATIONS[number];
