/**
 * Default Hotels/Lodges Content
 * Premium accommodation data for East Africa
 */

import safariHeroImg from '../../assets/images/safari_hero_1784973880507.jpg';
import luxuryLodgeImg from '../../assets/images/luxury_lodge_1784973897035.jpg';

export const DEFAULT_HOTELS = [
  {
    id: 'lodge-angama-mara',
    name: 'Angama Mara',
    location: 'Great Rift Valley, Maasai Mara, Kenya',
    country: 'Kenya' as const,
    tier: 'Ultra-Luxe Canvas' as const,
    category: 'Safari Lodge' as const,
    rating: 4.99,
    reviewsCount: 248,
    pricePerNight: 2800,
    ecoScore: 9.8,
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
      'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Perched 1,800 feet above the Mara Triangle on the edge of the Great Rift Valley, Angama Mara is a safari camp unlike any other. Fifty luminous tented suites float above the acacia-dotted plains, each with floor-to-ceiling Maasai-red canvas screens that transform with the light.',
    amenities: [
      'Floatplane airstrip with complimentary transfers',
      'Infinity pool overlooking the Mara Triangle',
      'Angama Photography Studio with Canon equipment',
      'Shamba Foundation cultural experiences',
      'Maasai Mara Reserve inclusion in nightly rate',
    ],
    roomTypes: [
      {
        id: 'room-angama-suite',
        name: 'Maasai Mara Tent Suite',
        description: '650-square-foot tented suite with unobstructed views of the Mara Triangle, hand-stitched Maasai blankets, and a private deck with daybed.',
        sizeSqFt: 650,
        bedType: 'Super-King Four-Poster',
        maxOccupancy: 2,
        pricePerNight: 2800,
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
        amenities: ['Rift Valley View Deck', 'Butler Service', 'Soaking Tub', 'Maasai Art Collection'],
        availableRooms: 50,
      },
    ],
    coordinates: { lat: -1.3622, lng: 35.0528 },
    checkInTime: '02:00 PM',
    checkOutTime: '11:00 AM',
    contactEmail: 'reservations@angama.com',
    contactPhone: '+254 711 777 777',
    featured: true,
  },
  {
    id: 'lodge-singita-sasakwa',
    name: 'Singita Sasakwa Lodge',
    location: 'Grumeti Reserve, Serengeti, Tanzania',
    country: 'Tanzania' as const,
    tier: 'Ultra-Luxe Canvas' as const,
    category: 'Bespoke Private Villa' as const,
    rating: 4.98,
    reviewsCount: 186,
    pricePerNight: 3200,
    ecoScore: 9.9,
    image: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
    ],
    description: 'Crowning the kopje overlooking the Serengeti plains, Singita Sasakwa Lodge offers a palatial Edwardian manor house experience with private plunge pools, a wine library, and an infinity pool overlooking the endless savanna.',
    amenities: [
      'Private airstrip with champagne arrival',
      'Sasakwa Spa with Ayurvedic treatments',
      'Vintage wine cellar with sommeliers',
      'Private game vehicles for all guests',
      'Swimming pool with panoramic plains views',
    ],
    roomTypes: [
      {
        id: 'room-sasakwa-cottage',
        name: 'Cottage Suite with Plunge Pool',
        description: 'Spacious self-contained cottage with colonial furnishings, en-suite bathroom, private deck, and personal plunge pool overlooking the Serengeti.',
        sizeSqFt: 1100,
        bedType: 'Antique King',
        maxOccupancy: 2,
        pricePerNight: 3200,
        image: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80',
        amenities: ['Plunge Pool', 'Butler Service', 'Wine Selection', 'Private Deck'],
        availableRooms: 6,
      },
    ],
    coordinates: { lat: -2.2917, lng: 34.2917 },
    checkInTime: '12:00 PM',
    checkOutTime: '11:00 AM',
    contactEmail: 'reservations@singita.com',
    contactPhone: '+255 784 900 900',
    featured: true,
  },
  {
    id: 'lodge-bisate',
    name: 'Bisate Lodge by Wilderness',
    location: 'Volcanoes National Park, Rwanda',
    country: 'Rwanda' as const,
    tier: 'Eco Luxury Lodge' as const,
    category: 'Safari Lodge' as const,
    rating: 4.97,
    reviewsCount: 142,
    pricePerNight: 2200,
    ecoScore: 9.9,
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
    ],
    description: 'Six opulent domed villas inspired by the royal palaces of old Rwanda, nestled in a Afro montane forest with views of the Virunga Volcanoes. Each villa features a private lounge, bedroom, bathroom, and deck with volcano panoramas.',
    amenities: [
      'Volcano panorama from each villa',
      'Guided nature walks through indigenous forest',
      'Community cultural experiences with local cooperatives',
      'Bird watching with expert Rwandan guides',
      'Mountain bike trails through bamboo forest',
    ],
    roomTypes: [
      {
        id: 'room-bisate-villa',
        name: 'Eco Luxury Villa',
        description: 'Spherical luxury villa constructed from volcanic stone and thatched roofing, featuring en-suite bathroom, fireplace, and private deck with panoramic volcano views.',
        sizeSqFt: 900,
        bedType: 'King Four-Poster',
        maxOccupancy: 2,
        pricePerNight: 2200,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
        amenities: ['Volcano View Deck', 'Fireplace', 'Soaking Tub', 'Forest Views'],
        availableRooms: 6,
      },
    ],
    coordinates: { lat: -1.4889, lng: 29.5891 },
    checkInTime: '02:00 PM',
    checkOutTime: '10:30 AM',
    contactEmail: 'bisate@wildernessdestinations.com',
    contactPhone: '+250 788 300 120',
    featured: true,
  },
  {
    id: 'lodge-gorilla-forest-camp',
    name: 'Sanctuary Gorilla Forest Camp',
    location: 'Bwindi Impenetrable National Park, Uganda',
    country: 'Uganda' as const,
    tier: 'Eco Luxury Lodge' as const,
    category: 'Luxury Tented Camp' as const,
    rating: 4.92,
    reviewsCount: 76,
    pricePerNight: 1450,
    ecoScore: 9.7,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
    ],
    description: 'The ONLY luxury camp situated inside the actual boundaries of Bwindi Impenetrable National Park. Wild mountain gorilla families regularly stroll right through the camp lawn.',
    amenities: [
      'Located Inside National Park Boundary',
      'Batwa Cultural Heritage Encounters',
      'Gorilla Habituation Specialist Guides',
      'Open-Air Forest Firepit',
      'Solar Heated Stone Baths',
    ],
    roomTypes: [
      {
        id: 'room-bwindi-tent',
        name: 'Forest Canopy Luxury Suite',
        description: 'Spacious canvas tent on elevated wooden platform with deep clawfoot soaking tub looking into ancient rainforest.',
        sizeSqFt: 850,
        bedType: 'Four-Poster King',
        maxOccupancy: 2,
        pricePerNight: 1450,
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
        amenities: ['Forest View Clawfoot Tub', 'Private Veranda', 'Personal Butler Service', 'Trekking Gear Drying Service'],
        availableRooms: 8,
      },
    ],
    coordinates: { lat: -1.0321, lng: 29.6821 },
    checkInTime: '12:00 PM',
    checkOutTime: '10:00 AM',
    contactEmail: 'bwindi@sanctuaryretreats.com',
    contactPhone: '+256 41 423 7100',
    featured: false,
  },
  {
    id: 'lodge-baraza-zanzibar',
    name: 'Baraza Resort & Spa Zanzibar',
    location: 'Bwejuu - Paje Beach, Zanzibar, Tanzania',
    country: 'Tanzania' as const,
    tier: 'Bespoke Private Villa' as const,
    category: 'Eco Beach Resort' as const,
    rating: 4.95,
    reviewsCount: 112,
    pricePerNight: 1250,
    ecoScore: 9.6,
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
    ],
    description: 'A 5-star all-inclusive luxury beach resort evoking the heritage of the Sultan of Zanzibar. Featuring hand-carved arches, brass lanterns, and private oceanfront plunge pools.',
    amenities: [
      'PADI 5-Star Dive Center',
      'Frangipani Spa & Underwater Music Pool',
      'Private Oceanfront Plunge Pools',
      'Sultanic Fine Dining',
      'Kitesurfing & Coral Reef Kayaking',
    ],
    roomTypes: [
      {
        id: 'room-baraza-ocean',
        name: 'Sultan Oceanfront Plunge Villa',
        description: 'Palatial beachfront villa with private plunge pool, daybed terrace, and direct white sand beach access.',
        sizeSqFt: 1600,
        bedType: 'Sultan Canopy King Bed',
        maxOccupancy: 2,
        pricePerNight: 1250,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
        amenities: ['Private Oceanfront Pool', 'Sultanic Bathing Room', 'All Inclusive Dining', 'Sunset Butler Service'],
        availableRooms: 12,
      },
    ],
    coordinates: { lat: -6.2231, lng: 39.5281 },
    checkInTime: '02:00 PM',
    checkOutTime: '11:00 AM',
    contactEmail: 'info@baraza-zanzibar.com',
    contactPhone: '+255 774 440 880',
    featured: false,
  },
  {
    id: 'lodge-giraffe-manor',
    name: 'Giraffe Manor & Sanctuary',
    location: 'Karen, Nairobi, Kenya',
    country: 'Kenya' as const,
    tier: 'Eco Luxury Lodge' as const,
    category: 'Heritage Manor' as const,
    rating: 4.97,
    reviewsCount: 210,
    pricePerNight: 1900,
    ecoScore: 9.8,
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
    heroImage: safariHeroImg as unknown as string,
    gallery: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
      luxuryLodgeImg as unknown as string,
    ],
    description: 'Iconic 1930s boutique manor house famous worldwide for its resident herd of Rothschild giraffes who poke their heads into second-floor windows during breakfast.',
    amenities: [
      'Interactive Giraffe Breakfast Experience',
      'Rothschild Giraffe Center Sanctuary',
      '12 Acres of Private Indigenous Forest',
      'Orchid House Afternoon Tea',
      'Karen Blixen Museum Access',
    ],
    roomTypes: [
      {
        id: 'room-giraffe-breakfast',
        name: 'Master Giraffe Window Suite',
        description: 'Second-floor heritage suite where giraffes regularly poke their long necks in for morning treats.',
        sizeSqFt: 950,
        bedType: 'Vintage Antique King',
        maxOccupancy: 2,
        pricePerNight: 1900,
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
        amenities: ['Giraffe Window Feeding Access', 'Antique Roll-Top Bath', 'Art Deco Furnishings', 'Private Balcony'],
        availableRooms: 4,
      },
    ],
    coordinates: { lat: -1.3761, lng: 36.7421 },
    checkInTime: '12:00 PM',
    checkOutTime: '10:00 AM',
    contactEmail: 'info@thesafaricollection.com',
    contactPhone: '+254 20 251 3166',
    featured: true,
  },
];

export type DefaultHotel = typeof DEFAULT_HOTELS[number];
