/**
 * Default Safari Packages/Itineraries Content
 * Premium curated safari packages
 */

import safariHeroImg from '../../assets/images/safari_hero_1784973880507.jpg';

export const DEFAULT_PACKAGES = [
  {
    id: 'pkg-great-migration',
    title: 'The Great Migration Spectacular',
    subtitle: 'Witness Nature\'s Greatest Wildlife Spectacle',
    destinations: ['Masai Mara', 'Serengeti'],
    countries: ['Kenya', 'Tanzania'] as const,
    durationDays: 7,
    durationNights: 6,
    priceUSD: 8500,
    luxuryTier: 'Ultra-Luxe Canvas' as const,
    rating: 4.98,
    reviewsCount: 156,
    heroImage: safariHeroImg as unknown as string,
    wildlifeTags: ['Great Wildebeest Migration', 'The Big Five', 'Predator Tracking'],
    includedInPrice: [
      'All luxury tented camp accommodations',
      'All meals and premium beverages',
      'Twice-daily scheduled game drives',
      'Internal bush flights between camps',
      'Park entry fees and conservation charges',
      'Experienced certified driver-guides',
      'Airport transfers and transport',
    ],
    excludedInPrice: [
      'International flights to/from Nairobi',
      'Travel insurance (mandatory)',
      'Visa fees',
      'Personal expenses and tips',
      'Premium wine and champagne selections',
      'Balloon safari upgrade',
    ],
    dayByDay: [
      {
        day: 1,
        title: 'Arrival in Nairobi',
        location: 'Nairobi, Kenya',
        description: 'Arrive at Jomo Kenyatta International Airport where our representative will meet you. Transfer to the historic Giraffe Manor for a welcome dinner overlooking the African sunset.',
        accommodation: 'Giraffe Manor - Heritage Suite',
        meals: 'Welcome Dinner',
        activities: ['Giraffe feeding experience', 'Welcome briefing'],
      },
      {
        day: 2,
        title: 'Flight to the Mara',
        location: 'Masai Mara, Kenya',
        description: 'Morning charter flight to the Masai Mara. Upon landing, your private guide will transfer you to Angama Mara, perched on the Rift Valley escarpment with panoramic views.',
        accommodation: 'Angama Mara - Maasai Suite',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Scenic flight over Rift Valley', 'Afternoon game drive', 'Sundowner cocktails'],
      },
      {
        day: 3,
        title: 'Great Migration River Crossing',
        location: 'Masai Mara, Kenya',
        description: 'Full day following the wildebeest migration. Position at strategic crossing points along the Mara River to witness thousands of animals making the dramatic crossing while crocodiles lurk below.',
        accommodation: 'Angama Mara - Maasai Suite',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Dawn hot air balloon (optional)', 'Full day migration tracking', 'Bush breakfast', 'Evening game drive'],
      },
      {
        day: 4,
        title: 'Big Cat Safari',
        location: 'Masai Mara, Kenya',
        description: 'Track the legendary Marsh Pride lions and elusive leopards with expert trackers. Visit a traditional Maasai manyatta for cultural immersion.',
        accommodation: 'Angama Mara - Maasai Suite',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Lion pride tracking', 'Maasai cultural visit', 'Night game drive'],
      },
      {
        day: 5,
        title: 'Crossing into Tanzania',
        location: 'Serengeti, Tanzania',
        description: 'Scenic drive across the border into the Serengeti. Enjoy a champagne picnic in the endless plains as you enter Tanzania\'s most iconic park.',
        accommodation: 'Singita Sasakwa Lodge - Cottage Suite',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Cross-border transfer', 'Picnic in the Serengeti', 'Evening game drive'],
      },
      {
        day: 6,
        title: 'Serengeti Exploration',
        location: 'Serengeti, Tanzania',
        description: 'Explore the central Serengeti, known for excellent year-round wildlife sightings. Search for cheetahs on the open plains and enjoy sunset drinks atop a granite kopje.',
        accommodation: 'Singita Sasakwa Lodge - Cottage Suite',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Full day game drive', 'Kopje sundowners', 'Infinity pool relaxation'],
      },
      {
        day: 7,
        title: 'Farewell & Departure',
        location: 'Serengeti to Nairobi',
        description: 'Morning game drive followed by charter flight back to Nairobi. Connect with your international departure or extend your safari.',
        accommodation: 'N/A',
        meals: 'Breakfast, Brunch',
        activities: ['Final morning game drive', 'Charter flight to Nairobi', 'Airport transfer'],
      },
    ],
    migrationSeasonMatch: true,
    gameDrivesPerDay: 2,
    transferType: 'Bush Charter Flight + 4x4' as const,
    cancellationPolicy: 'Free cancellation up to 30 days before departure. 50% refund between 30-15 days. No refund within 15 days.',
    featured: true,
  },
  {
    id: 'pkg-gorilla-discovery',
    title: 'Rwanda Gorilla Discovery',
    subtitle: 'Encounter the Gentle Giants of the Virungas',
    destinations: ['Volcanoes National Park', 'Lake Kivu'],
    countries: ['Rwanda'] as const,
    durationDays: 5,
    durationNights: 4,
    priceUSD: 9500,
    luxuryTier: 'Eco Luxury Lodge' as const,
    rating: 4.97,
    reviewsCount: 89,
    heroImage: safariHeroImg as unknown as string,
    wildlifeTags: ['Mountain Gorillas & Primates'],
    includedInPrice: [
      'Luxury villa accommodations',
      'All meals including fine dining',
      'Gorilla trekking permits (2 encounters)',
      'Golden monkey tracking permit',
      'Dian Fossey tomb hike',
      'Private vehicle and expert guide',
      'Airport transfers',
    ],
    excludedInPrice: [
      'International flights',
      'Travel insurance',
      'Visa fees',
      'Personal expenses',
      'Laundry services',
      'Spa treatments',
    ],
    dayByDay: [
      {
        day: 1,
        title: 'Arrival in Kigali',
        location: 'Kigali, Rwanda',
        description: 'Arrive at Kigali International Airport. Our guide will meet you for a city tour including the Genocide Memorial before transferring to your luxury villa.',
        accommodation: 'Bisate Lodge - Eco Luxury Villa',
        meals: 'Welcome Dinner',
        activities: ['Kigali city tour', 'Genocide memorial visit', 'Hotel briefing'],
      },
      {
        day: 2,
        title: 'First Gorilla Trek',
        location: 'Volcanoes National Park',
        description: 'Early morning departure for your first gorilla trek. After the trek, relax with a spa treatment and cultural experience at the lodge.',
        accommodation: 'Bisate Lodge - Eco Luxury Villa',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Gorilla trekking (2 hours)', 'Lodge relaxation', 'Cultural experience'],
      },
      {
        day: 3,
        title: 'Second Gorilla Trek & Golden Monkeys',
        location: 'Volcanoes National Park',
        description: 'Second gorilla encounter followed by golden monkey tracking in the bamboo forests. Evening transfer to Lake Kivu for sunset dhow cruise.',
        accommodation: 'One&Only Nyungwe House',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Second gorilla trek', 'Golden monkey tracking', 'Lake Kivu sunset cruise'],
      },
      {
        day: 4,
        title: 'Canopy Walk & Tea Plantation',
        location: 'Nyungwe Forest',
        description: 'Morning canopy walk above the forest floor, followed by a visit to the Gisakura tea plantation. Farewell dinner at the lodge.',
        accommodation: 'One&Only Nyungwe House',
        meals: 'Breakfast, Lunch, Farewell Dinner',
        activities: ['Canopy walk', 'Tea plantation tour', 'Bird watching'],
      },
      {
        day: 5,
        title: 'Departure',
        location: 'Kigali',
        description: 'Morning transfer to Kigali for your international departure. Option to visit the Kimironko market for last-minute shopping.',
        accommodation: 'N/A',
        meals: 'Breakfast',
        activities: ['Transfer to Kigali', 'Market visit (optional)'],
      },
    ],
    migrationSeasonMatch: false,
    gameDrivesPerDay: 1,
    transferType: '4x4 Executive Land Cruiser' as const,
    cancellationPolicy: 'Free cancellation up to 45 days before departure. Gorilla permits are non-refundable.',
    featured: true,
  },
  {
    id: 'pkg-uganda-primates',
    title: 'Uganda Primate Safari',
    subtitle: 'Mountain Gorillas, Chimpanzees & More',
    destinations: ['Bwindi Impenetrable Forest', 'Queen Elizabeth National Park'],
    countries: ['Uganda'] as const,
    durationDays: 6,
    durationNights: 5,
    priceUSD: 7200,
    luxuryTier: 'Eco Luxury Lodge' as const,
    rating: 4.95,
    reviewsCount: 67,
    heroImage: safariHeroImg as unknown as string,
    wildlifeTags: ['Mountain Gorillas & Primates'],
    includedInPrice: [
      'Luxury tented camp accommodations',
      'All meals',
      'Gorilla trekking permit',
      'Chimpanzee trekking permit',
      'Game drives in Queen Elizabeth NP',
      'Private guide and vehicle',
      'Internal transfers',
    ],
    excludedInPrice: [
      'International flights',
      'Travel insurance',
      'Visa fees',
      'Personal expenses',
      'Laundry',
    ],
    dayByDay: [
      {
        day: 1,
        title: 'Arrival in Entebbe',
        location: 'Entebbe, Uganda',
        description: 'Arrive at Entebbe International Airport. Transfer to Lake Victoria for overnight at a luxury lakeside retreat.',
        accommodation: 'Lake Victoria Serena Resort',
        meals: 'Dinner',
        activities: ['Airport transfer', 'Lakeside relaxation'],
      },
      {
        day: 2,
        title: 'Flight to Bwindi',
        location: 'Bwindi Impenetrable Forest',
        description: 'Morning flight to Bwindi. Afternoon at leisure at your luxury forest camp before tomorrow\'s gorilla trek.',
        accommodation: 'Sanctuary Gorilla Forest Camp',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Flight to Bwindi', 'Camp orientation'],
      },
      {
        day: 3,
        title: 'Gorilla Trekking',
        location: 'Bwindi Impenetrable Forest',
        description: 'Full day gorilla trekking experience. Spend up to one hour with a wild mountain gorilla family in their natural habitat.',
        accommodation: 'Sanctuary Gorilla Forest Camp',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Gorilla trek (2-6 hours)', 'Forest walk', 'Batwa cultural visit'],
      },
      {
        day: 4,
        title: 'Transfer to Queen Elizabeth NP',
        location: 'Queen Elizabeth National Park',
        description: 'Scenic drive south to Queen Elizabeth National Park. Afternoon game drive along the Kasenyi track.',
        accommodation: 'Mweya Safari Lodge',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Scenic drive', 'Afternoon game drive', 'Launch cruise (optional)'],
      },
      {
        day: 5,
        title: 'Tree Climbing Lions & Chimps',
        location: 'Queen Elizabeth National Park',
        description: 'Morning search for tree-climbing lions in Ishasha sector. Afternoon chimpanzee trekking in Kyambura Gorge.',
        accommodation: 'Mweya Safari Lodge',
        meals: 'Breakfast, Lunch, Dinner',
        activities: ['Ishasha lion tracking', 'Chimp trek in gorge', 'Evening game drive'],
      },
      {
        day: 6,
        title: 'Departure',
        location: 'Entebbe',
        description: 'Morning game drive and transfer to Kasese airstrip for flight back to Entebbe and international connections.',
        accommodation: 'N/A',
        meals: 'Breakfast',
        activities: ['Final game drive', 'Flight to Entebbe'],
      },
    ],
    migrationSeasonMatch: false,
    gameDrivesPerDay: 2,
    transferType: '4x4 Executive Land Cruiser' as const,
    cancellationPolicy: 'Free cancellation up to 30 days. Gorilla permits non-refundable.',
    featured: false,
  },
];

export type DefaultPackage = typeof DEFAULT_PACKAGES[number];
