/**
 * Default Partners Content
 * Conservation, government, and tourism partners
 */

export const DEFAULT_PARTNERS = [
  {
    id: 'partner-kenya-tourism',
    name: 'Kenya Tourist Board',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/120px-Flag_of_Kenya.svg.png',
    website: 'https://www.tourism.go.ke',
    description: 'Official government tourism board promoting Kenya as a premier safari destination.',
    type: 'government' as const,
    tier: 'platinum' as const,
    featured: true,
  },
  {
    id: 'partner-tanza-tourism',
    name: 'Tanzania Tourist Board',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Flag_of_Tanzania.svg/120px-Flag_of_Tanzania.svg.png',
    website: 'https://www.tanzaniatourism.go.tz',
    description: 'Official tourism authority for Tanzania, home to the Serengeti and Mount Kilimanjaro.',
    type: 'government' as const,
    tier: 'platinum' as const,
    featured: true,
  },
  {
    id: 'partner-uganda-wildlife',
    name: 'Uganda Wildlife Authority',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/120px-Flag_of_Uganda.svg.png',
    website: 'https://www.ugandawildlife.org',
    description: 'Managing Uganda\'s national parks and wildlife reserves including Bwindi and Queen Elizabeth.',
    type: 'government' as const,
    tier: 'platinum' as const,
    featured: true,
  },
  {
    id: 'partner-rwanda-tourism',
    name: 'Rwanda Development Board',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/120px-Flag_of_Rwanda.svg.png',
    website: 'https://www.rdb.rw',
    description: 'Promoting Rwanda\'s tourism including gorilla trekking in Volcanoes National Park.',
    type: 'government' as const,
    tier: 'platinum' as const,
    featured: true,
  },
  {
    id: 'partner-african-wildlife',
    name: 'African Wildlife Foundation',
    logo: 'https://example.com/awf-logo.png',
    website: 'https://www.awf.org',
    description: 'Conservation organization working to protect wildlife and wild lands across Africa.',
    type: 'conservation' as const,
    tier: 'gold' as const,
    featured: true,
  },
  {
    id: 'partner-safarilink',
    name: 'Safarilink Aviation',
    logo: 'https://example.com/safarilink-logo.png',
    website: 'https://www.safarilinkaviation.com',
    description: 'East Africa\'s premier bush airline connecting major parks and reserves.',
    type: 'airline' as const,
    tier: 'gold' as const,
    featured: false,
  },
  {
    id: 'partner-air-kenya',
    name: 'AirKenya Express',
    logo: 'https://example.com/airkenya-logo.png',
    website: 'https://www.airkenya.com',
    description: 'Regional airline serving Kenya\'s national parks and remote safari destinations.',
    type: 'airline' as const,
    tier: 'gold' as const,
    featured: false,
  },
  {
    id: 'partner-singita',
    name: 'Singita',
    logo: 'https://example.com/singita-logo.png',
    website: 'https://www.singita.com',
    description: 'Luxury safari lodge operator with award-winning properties in Tanzania and South Africa.',
    type: 'hotel_chain' as const,
    tier: 'gold' as const,
    featured: true,
  },
  {
    id: 'partner-and-beyond',
    name: '&Beyond',
    logo: 'https://example.com/andbeyond-logo.png',
    website: 'https://www.andbeyond.com',
    description: 'Luxury experiential travel company operating camps across Africa.',
    type: 'hotel_chain' as const,
    tier: 'gold' as const,
    featured: false,
  },
  {
    id: 'partner-wilderness',
    name: 'Wilderness Safaris',
    logo: 'https://example.com/wilderness-logo.png',
    website: 'https://www.wilderness-safaris.com',
    description: 'Eco-luxury safari operator committed to conservation and community development.',
    type: 'hotel_chain' as const,
    tier: 'gold' as const,
    featured: false,
  },
];

export type DefaultPartner = typeof DEFAULT_PARTNERS[number];
